# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sx_user', '0001_initial'),
        ('sx_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('isTrue', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_store.GoodsValue')),
            ],
            options={
                'db_table': 'sx_order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('o_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('o_date', models.DateTimeField(auto_now=True)),
                ('o_pay', models.BooleanField(default=False)),
                ('o_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('o_address', models.CharField(max_length=150)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_user.UserModel')),
            ],
            options={
                'db_table': 'sx_order',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_store.GoodsValue')),
            ],
            options={
                'db_table': 'sx_sales',
            },
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_order.OrderModel'),
        ),
    ]
