# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sx_kind',
            },
        ),
        migrations.CreateModel(
            name='GoodsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_img', models.ImageField(upload_to='shop')),
                ('g_num', models.CharField(max_length=100)),
                ('g_price', models.FloatField(default=0)),
                ('g_unit', models.CharField(default='500g', max_length=20)),
                ('g_repertory', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_store.ArticleCategory')),
            ],
            options={
                'db_table': 'sx_goods',
            },
        ),
    ]
