# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sx_store', '0002_remove_goodsvalue_gtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsvalue',
            name='isDelete',
        ),
    ]
